/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DotComponent {
        "customClass"?: string;
        "orientation": 'horizontal' | 'vertical';
        "size": 'default' | 'sm';
        "variant": 'feint' | 'dark';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface DotComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDotComponentElement;
}
declare global {
    interface HTMLDotComponentElementEventMap {
        "dotsClick": void;
    }
    interface HTMLDotComponentElement extends Components.DotComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDotComponentElementEventMap>(type: K, listener: (this: HTMLDotComponentElement, ev: DotComponentCustomEvent<HTMLDotComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDotComponentElementEventMap>(type: K, listener: (this: HTMLDotComponentElement, ev: DotComponentCustomEvent<HTMLDotComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDotComponentElement: {
        prototype: HTMLDotComponentElement;
        new (): HTMLDotComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dot-component": HTMLDotComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DotComponent {
        "customClass"?: string;
        "onDotsClick"?: (event: DotComponentCustomEvent<void>) => void;
        "orientation"?: 'horizontal' | 'vertical';
        "size"?: 'default' | 'sm';
        "variant"?: 'feint' | 'dark';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dot-component": DotComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dot-component": LocalJSX.DotComponent & JSXBase.HTMLAttributes<HTMLDotComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
